# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_me": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Sebastian Rettig.github.io/nbdev_test/"

git_url = "https://github.com/Sebastian Rettig/nbdev_test/tree/master/"

def custom_doc_links(name): return None
