# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_me']

# Cell
def print_me(content = None):
    "A test function to print something. `content`, an optional content to print."
    print(content) if content is not None else print("me")